import type { ProviderPreset, ProviderSetting } from './types.js';

export const PROVIDER_PRESETS: ProviderPreset[] = [
  {
    providerId: 'openai-compatible',
    displayName: 'OpenAI-compatible',
    baseUrl: 'https://api.openai.com/v1',
    recommendedModels: ['gpt-4.1', 'gpt-4.1-mini', 'o4-mini'],
    authType: 'apiKey',
    docsHint: 'OpenAI-compatible /v1 chat completions or responses endpoint.',
    networkHint: 'Requires outbound HTTPS access.',
    needsApiKey: true,
    supportsStreaming: true,
    supportsVision: true,
    defaultTimeout: 60_000,
  },
  {
    providerId: 'deepseek',
    displayName: 'DeepSeek',
    baseUrl: 'https://api.deepseek.com/v1',
    recommendedModels: ['deepseek-chat', 'deepseek-reasoner'],
    authType: 'apiKey',
    docsHint: 'DeepSeek OpenAI-compatible API.',
    networkHint: 'Requires outbound HTTPS access to api.deepseek.com.',
    needsApiKey: true,
    supportsStreaming: true,
    supportsVision: false,
    defaultTimeout: 60_000,
  },
  {
    providerId: 'doubao-volcano-ark',
    displayName: 'Doubao / Volcano Ark',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    recommendedModels: ['doubao-seed-1-6', 'doubao-1-5-pro'],
    authType: 'apiKey',
    docsHint: 'Volcano Ark OpenAI-compatible endpoint.',
    networkHint: 'Mainland China endpoint; check corporate proxy rules.',
    needsApiKey: true,
    supportsStreaming: true,
    supportsVision: true,
    defaultTimeout: 60_000,
  },
  {
    providerId: 'openrouter',
    displayName: 'OpenRouter',
    baseUrl: 'https://openrouter.ai/api/v1',
    recommendedModels: ['openai/gpt-4.1', 'anthropic/claude-3.7-sonnet', 'google/gemini-2.5-pro'],
    authType: 'apiKey',
    docsHint: 'OpenRouter model router using OpenAI-compatible requests.',
    networkHint: 'Requires OpenRouter API key and HTTPS access.',
    needsApiKey: true,
    supportsStreaming: true,
    supportsVision: true,
    defaultTimeout: 90_000,
  },
  {
    providerId: 'ollama-local',
    displayName: 'Ollama local',
    baseUrl: 'http://127.0.0.1:11434/v1',
    recommendedModels: ['llama3.1', 'qwen2.5-coder', 'deepseek-r1'],
    authType: 'none',
    docsHint: 'Local Ollama OpenAI-compatible endpoint.',
    networkHint: 'Localhost only; no external network required.',
    needsApiKey: false,
    supportsStreaming: true,
    supportsVision: false,
    defaultTimeout: 120_000,
  },
  {
    providerId: 'claude-compatible',
    displayName: 'Claude-compatible',
    baseUrl: 'https://api.anthropic.com/v1',
    recommendedModels: ['claude-sonnet-4-20250514', 'claude-3-7-sonnet-latest'],
    authType: 'apiKey',
    docsHint: 'Claude-compatible provider. Use vendor-specific bridge if needed.',
    networkHint: 'Requires outbound HTTPS access.',
    needsApiKey: true,
    supportsStreaming: true,
    supportsVision: true,
    defaultTimeout: 90_000,
  },
  {
    providerId: 'gemini-compatible',
    displayName: 'Gemini-compatible',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta',
    recommendedModels: ['gemini-2.5-pro', 'gemini-2.5-flash'],
    authType: 'apiKey',
    docsHint: 'Gemini-compatible provider; model names vary by account.',
    networkHint: 'Requires outbound HTTPS access.',
    needsApiKey: true,
    supportsStreaming: true,
    supportsVision: true,
    defaultTimeout: 90_000,
  },
  {
    providerId: 'custom-provider',
    displayName: 'Custom Provider',
    baseUrl: '',
    recommendedModels: [],
    authType: 'custom',
    docsHint: 'Custom endpoint. Verify base URL, auth header style, and model name.',
    networkHint: 'Network behavior depends on the custom endpoint.',
    needsApiKey: true,
    supportsStreaming: false,
    supportsVision: false,
    defaultTimeout: 60_000,
  },
];

export function presetToProvider(
  preset: ProviderPreset,
  overrides: Partial<ProviderSetting> = {},
): Omit<ProviderSetting, 'id'> & { id?: string } {
  const modelName = overrides.modelName || preset.recommendedModels[0] || '';
  return {
    providerId: preset.providerId,
    providerName: overrides.providerName || preset.displayName,
    displayName: preset.displayName,
    baseUrl: overrides.baseUrl ?? preset.baseUrl,
    apiKey: overrides.apiKey ?? '',
    modelName,
    recommendedModels: preset.recommendedModels,
    authType: preset.authType,
    docsHint: preset.docsHint,
    networkHint: preset.networkHint,
    needsApiKey: preset.needsApiKey,
    supportsStreaming: preset.supportsStreaming,
    supportsVision: preset.supportsVision,
    defaultTimeout: preset.defaultTimeout,
    lastTestStatus: 'untested',
    enabled: overrides.enabled ?? true,
    memoryEnabled: overrides.memoryEnabled ?? true,
    memoryInjectionMode: overrides.memoryInjectionMode ?? 'balanced',
    maxMemoryItems: overrides.maxMemoryItems ?? 10,
    maxMemoryChars: overrides.maxMemoryChars ?? 8000,
  };
}

export function findProviderPreset(providerId: string): ProviderPreset | undefined {
  return PROVIDER_PRESETS.find((preset) => preset.providerId === providerId);
}
