// ── Core Data Models ──
// ── IPC channel names ──
export const IPC_CHANNELS = {
    // Storage
    STORAGE_GET: 'storage:get',
    STORAGE_SET: 'storage:set',
    STORAGE_DELETE: 'storage:delete',
    STORAGE_GET_ALL: 'storage:getAll',
    // Projects
    PROJECT_LIST: 'project:list',
    PROJECT_GET: 'project:get',
    PROJECT_CREATE: 'project:create',
    PROJECT_UPDATE: 'project:update',
    PROJECT_DELETE: 'project:delete',
    // Tasks
    TASK_LIST: 'task:list',
    TASK_CREATE: 'task:create',
    TASK_UPDATE: 'task:update',
    TASK_DELETE: 'task:delete',
    // Prompts
    PROMPT_LIST: 'prompt:list',
    PROMPT_CREATE: 'prompt:create',
    PROMPT_UPDATE: 'prompt:update',
    PROMPT_DELETE: 'prompt:delete',
    // Runs
    RUN_LIST: 'run:list',
    RUN_CREATE: 'run:create',
    // Git
    GIT_LOG: 'git:log',
    GIT_STATUS: 'git:status',
    GIT_SUMMARY: 'git:summary',
    // Memory
    MEMORY_LIST: 'memory:list',
    MEMORY_GET: 'memory:get',
    MEMORY_CREATE: 'memory:create',
    MEMORY_UPDATE: 'memory:update',
    MEMORY_DELETE: 'memory:delete',
    MEMORY_EXPORT: 'memory:export',
    MEMORY_IMPORT: 'memory:import',
    MEMORY_GENERATE_CONTEXT: 'memory:generateContext',
    // Settings
    SETTINGS_GET: 'settings:get',
    SETTINGS_SET: 'settings:set',
    SETTINGS_GET_ALL: 'settings:getAll',
    PROVIDER_LIST: 'provider:list',
    PROVIDER_CREATE: 'provider:create',
    PROVIDER_UPDATE: 'provider:update',
    PROVIDER_DELETE: 'provider:delete',
    // Export
    EXPORT_MARKDOWN: 'export:markdown',
    EXPORT_JSON: 'export:json',
    // Skills
    SKILLS_LIST: 'skills:list',
    SKILL_READ: 'skill:read',
    // App
    APP_INFO: 'app:info',
    GET_DATA_PATH: 'app:dataPath',
    // Dialog
    DIALOG_OPEN: 'dialog:open',
};
//# sourceMappingURL=types.js.map