export {
  authConfig,
  normalizeEmail,
  isValidEmail,
  assertStrongEnoughPassword,
  hashPassword,
  verifyPassword,
  hashToken,
  createSessionToken,
  createTemporaryPassword,
  createSession,
  isSessionActive,
  toPublicUser,
  toSessionUser,
  createDefaultAdmin,
  validateUserStatus,
  createUserFromRequest,
  getLockUntil,
} from '../shared/authCore.js';
