import type {
  NexusRuntimeProfile,
  NexusRuntimeProfileKind,
  ProviderSetting,
} from '../../../shared/types.js';
import storage from '../../storage.js';

const GATEWAY_ROOT = 'http://127.0.0.1:8317';
const GATEWAY_V1 = `${GATEWAY_ROOT}/v1`;

function toToml(values: Record<string, string>): string {
  return Object.entries(values)
    .map(([key, value]) => `${key} = ${JSON.stringify(value)}`)
    .join('\n');
}

function toYaml(values: Record<string, string>): string {
  return Object.entries(values)
    .map(([key, value]) => `${key}: ${JSON.stringify(value)}`)
    .join('\n');
}

function profileFor(kind: NexusRuntimeProfileKind, provider?: ProviderSetting): NexusRuntimeProfile {
  const model = provider?.modelName || 'localai-nexus-diagnostic';
  const baseEnv = {
    LOCALAI_NEXUS_BASE_URL: GATEWAY_ROOT,
    LOCALAI_NEXUS_V1_BASE_URL: GATEWAY_V1,
    LOCALAI_NEXUS_MODEL: model,
  };
  const diagnostics = [
    `Gateway root Base URL: ${GATEWAY_ROOT}`,
    `OpenAI-compatible /v1 Base URL: ${GATEWAY_V1}`,
    'If the client appends /v1 automatically, use the root Base URL.',
    'If the client does not append /v1, use the /v1 Base URL.',
  ];
  const name =
    kind === 'codex'
      ? 'Codex LocalAI Nexus Profile'
      : kind === 'claude-code'
        ? 'Claude Code LocalAI Nexus Profile'
        : kind === 'cli'
          ? 'CLI LocalAI Nexus Profile'
          : 'Custom LocalAI Nexus Profile';
  const env = kind === 'claude-code'
    ? { ...baseEnv, ANTHROPIC_BASE_URL: GATEWAY_ROOT, ANTHROPIC_MODEL: model }
    : { ...baseEnv, OPENAI_BASE_URL: GATEWAY_V1, OPENAI_MODEL: model };
  const command =
    kind === 'codex'
      ? `set OPENAI_BASE_URL=${GATEWAY_V1} && set OPENAI_MODEL=${model}`
      : kind === 'claude-code'
        ? `set ANTHROPIC_BASE_URL=${GATEWAY_ROOT} && set ANTHROPIC_MODEL=${model}`
        : `set OPENAI_BASE_URL=${GATEWAY_V1} && set OPENAI_MODEL=${model}`;
  return {
    id: kind,
    name,
    kind,
    baseUrl: kind === 'codex' || kind === 'cli' ? GATEWAY_V1 : GATEWAY_ROOT,
    model,
    providerRef: provider?.id,
    env,
    json: {
      baseUrl: kind === 'codex' || kind === 'cli' ? GATEWAY_V1 : GATEWAY_ROOT,
      model,
      providerRef: provider?.id,
      note: 'Generated by LocalAI Nexus Runtime Switcher.',
    },
    toml: toToml(env),
    yaml: toYaml(env),
    diagnostics,
    command,
    redaction: 'no-secrets',
    updatedAt: new Date().toISOString(),
  };
}

export async function generateRuntimeProfiles(): Promise<NexusRuntimeProfile[]> {
  const providers = await storage.getAll<ProviderSetting>('providerSettings');
  const activeRef = String((await storage.getById<{ id: string; value?: unknown }>('settings', 'activeProviderRef'))?.value ?? '');
  const activeProvider = providers.find((provider) => provider.id === activeRef) ?? providers.find((provider) => provider.enabled !== false);
  const profiles = (['codex', 'claude-code', 'cli', 'custom'] as NexusRuntimeProfileKind[])
    .map((kind) => profileFor(kind, activeProvider));
  for (const profile of profiles) {
    const existing = await storage.getById('runtimeProfiles', profile.id);
    if (existing) await storage.update('runtimeProfiles', profile.id, profile as never);
    else await storage.create('runtimeProfiles', profile as never);
  }
  return profiles;
}
